site_name: carbyrator

docs_dir: docs
site_dir: ../docs

theme:
  name: simple-blog

nav:
  - Главная: index.md
  - Обо мне: about.md
  - Лабораторные работы:
      - Обзор: projects.md
      - Проект 1. Task Tracker (TODO-приложение): projects/lab1.md
      - Проект 2. Оптимизация вычислений в Python: projects/lab2.md
      - Проект 3. CRUD-приложение с SQLite и MVC: projects/lab3.md
      - Проект 4. Основы NumPy массивы и векторные операции: projects/LR-2.md

plugins:
  - search

extra_css:
  - stylesheets/extra.css