site_name: My Docs

docs_dir: docs
site_dir: ../docs

theme:
  name: dracula

nav:
  - Главная: index.md
  - Обо мне: about.md
  - Проекты: projects.md

plugins:
  - search

extra_css:
  - stylesheets/extra.css